### PR TITLE
Fix #465

### LINKED ISSUE #465: create_channel on a connection intentionally closed by the user shown immediately throw an argument/illegal state exception
Hi, 

I just found this (weird?) behaviour: when creating a channel after a connection.close Bunny tries to recover from a network failure thus failing and getting into a Timeout exception. Is the client supposed to behave in this way? See attached code:

```ruby
require 'bunny'

client = Bunny.new
client.start

channel = client.create_channel
channel.default_exchange.publish "hello"

client.stop

client.create_channel

# Bunny tries to recover from a network failure

#<Bunny::Session:0x7fd0b8152300 guest@127.0.0.1:5672, vhost=/, addresses=[127.0.0.1:5672]>: Recovering from a network failure...
#<Bunny::Session:0x7fd0b8152300 guest@127.0.0.1:5672, vhost=/, addresses=[127.0.0.1:5672]>: Retrying connection on next host in line: 127.0.0.1:5672

# Timeout::Error (Timeout::Error)
```

Thanks.

### PR DESCRIPTION
**Pull request by madAle**
I provided some specs related to #465 and also suggested a fix that I hope correctly addresses the issue.

### CODE REVIEW

File: spec/issues/issue465_spec.rb [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+    describe '#create_channel' do
+      it 'should raise an exception' do
+        expect {
+          connection.create_channel
+        }.to raise_error(Bunny::ConnectionManuallyClosed)
+      end
+    end
+
+    describe '#start' do
+      it 'should be possible to reopen it' do
```
Comment (michaelklishin) [inline spec/issues/issue465_spec.rb]: I didn't plan on supporting this but if we do and it's actually a safe thing to do in practice, no objections from me.

File: lib/bunny/exceptions.rb [hunk 2]
```diff
@@ -97,6 +97,12 @@ def initialize(frame)
     end
   end
 
+  class ConnectionManuallyClosed < Exception
```
Comment (michaelklishin) [inline lib/bunny/exceptions.rb]: Other clients use `AlreadyClosedException` (Java) and similar names. I'd prefer that.

File: lib/bunny/exceptions.rb [hunk 3]
```diff
@@ -97,6 +97,12 @@ def initialize(frame)
...
+    def initialize
+      super('Connection has been manually closed. Call #start to reopen it')
```
Comment (michaelklishin) [inline lib/bunny/exceptions.rb]: I'm not sure how I feel about recommending this. It may or may not be safe and I don't think we should support reopening at all. It is hard and is not any easier to use than opening a new connection.
So let's drop the recommendation.

Comment (madAle) [inline lib/bunny/exceptions.rb]: I agree.

File: spec/issues/issue465_spec.rb (hunk 1 above)
Comment (madAle) [inline spec/issues/issue465_spec.rb]: Ok, given that I'll remove the recommendation given in current ConnectionManuallyClosed exception (name will change), I'll also drop these specs in order to maintain things coherent and not add official support for connection reopen. @michaelklishin do you agree?

Comment (michaelklishin) [inline spec/issues/issue465_spec.rb]: 👍

**Comment by michaelklishin** [comment]
Thank you!
